[package]
name = "rendezvous"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
foldhash = "0.1.5"
rand = "0.9"
wasm-bindgen = "0.2.100"
itertools = "0.14"
rand_distr = "0.5"
slotmap = "1"

getrandom = { version = "0.3", features = ["wasm_js"] }
